# Development docker-compose override
version: '3.8'

services:
  app:
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - RELOAD=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    environment:
      POSTGRES_DB: turn_dev_db
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: