"""Add project collaborators

Revision ID: a24ca9246672
Revises: 94cf4cf28bda
Create Date: 2025-11-04 13:59:04.721136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24ca9246672'
down_revision: Union[str, None] = '94cf4cf28bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type if it doesn't exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'collaborationstatus') THEN
                CREATE TYPE collaborationstatus AS ENUM ('INVITED', 'ACCEPTED', 'DECLINED');
            END IF;
        END$$;
        """
    )

    # Create table without enum column first
    op.execute(
        """
        CREATE TABLE project_collaborators (
            id SERIAL PRIMARY KEY,
            project_id INTEGER NOT NULL,
            collaborator_user_id INTEGER,
            collaborator_email VARCHAR(320),
            role VARCHAR(50) NOT NULL,
            permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
            invite_message TEXT,
            invitation_status collaborationstatus NOT NULL,
            invited_by_user_id INTEGER NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT fk_project_collaborators_collaborator_user_id_users 
                FOREIGN KEY(collaborator_user_id) REFERENCES users(id) ON DELETE SET NULL,
            CONSTRAINT fk_project_collaborators_invited_by_user_id_users 
                FOREIGN KEY(invited_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_collaborators_project_id_project_simulations 
                FOREIGN KEY(project_id) REFERENCES project_simulations(id) ON DELETE CASCADE
        )
        """
    )
    op.create_index('idx_project_collaborators_email', 'project_collaborators', ['collaborator_email'], unique=False)
    op.create_index('idx_project_collaborators_project', 'project_collaborators', ['project_id'], unique=False)
    op.create_index('idx_project_collaborators_project_email', 'project_collaborators', ['project_id', 'collaborator_email'], unique=False)
    op.create_index('idx_project_collaborators_project_user', 'project_collaborators', ['project_id', 'collaborator_user_id'], unique=False)
    op.create_index('idx_project_collaborators_status', 'project_collaborators', ['invitation_status'], unique=False)
    op.create_index('idx_project_collaborators_user', 'project_collaborators', ['collaborator_user_id'], unique=False)

    with op.batch_alter_table('forum_categories', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forum_category_parent', 'forum_categories', ['parent_category_id'], ['id'], use_alter=True)

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forum_comment_parent', 'forum_comments', ['parent_comment_id'], ['id'], use_alter=True)

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forum_post_accepted_answer', 'forum_comments', ['accepted_answer_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_post_accepted_answer', type_='foreignkey')

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_comment_parent', type_='foreignkey')

    with op.batch_alter_table('forum_categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_category_parent', type_='foreignkey')

    op.drop_index('idx_project_collaborators_email', table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_project', table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_project_email', table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_project_user', table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_status', table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_user', table_name='project_collaborators')

    op.drop_table('project_collaborators')
    op.execute("DROP TYPE IF EXISTS collaborationstatus")
    # ### end Alembic commands ###